// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfXOnJSnSxPL1uExYJWbzhITm0Z9ZIQY',
    appId: '1:920109505885:web:2688546cca10c272925cb4',
    messagingSenderId: '920109505885',
    projectId: 'chatlysper',
    authDomain: 'chatlysper.firebaseapp.com',
    storageBucket: 'chatlysper.appspot.com',
    measurementId: 'G-4TH1FP3CSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMXwdwlcROLHzy65MOfYnaFJXEQoydnA',
    appId: '1:920109505885:android:be37320803a2dc67925cb4',
    messagingSenderId: '920109505885',
    projectId: 'chatlysper',
    storageBucket: 'chatlysper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Z2lE_NxHFhZNnrEGKrwdh4QTb872r9M',
    appId: '1:920109505885:ios:c8e507327d05ee9d925cb4',
    messagingSenderId: '920109505885',
    projectId: 'chatlysper',
    storageBucket: 'chatlysper.appspot.com',
    iosBundleId: 'com.example.chatlysperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Z2lE_NxHFhZNnrEGKrwdh4QTb872r9M',
    appId: '1:920109505885:ios:c8e507327d05ee9d925cb4',
    messagingSenderId: '920109505885',
    projectId: 'chatlysper',
    storageBucket: 'chatlysper.appspot.com',
    iosBundleId: 'com.example.chatlysperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqfXOnJSnSxPL1uExYJWbzhITm0Z9ZIQY',
    appId: '1:920109505885:web:1d788c6f5bf0c7b9925cb4',
    messagingSenderId: '920109505885',
    projectId: 'chatlysper',
    authDomain: 'chatlysper.firebaseapp.com',
    storageBucket: 'chatlysper.appspot.com',
    measurementId: 'G-CZVW7YVCQG',
  );
}
